import json

with open('c:\\projects\\cissp\\scenarios_fix_1.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

replacements = {
    257: [
        "The correct answer is 'Verify whether this is authorized maintenance activity' because the activity comes from a legitimate service account. Determining authorization avoids disrupting legitimate business operations unnecessarily.\n\n'Disable the service account immediately' is incorrect because disabling a legitimate service account without verification could cause immediate and widespread system outages for automated business processes.\n\n'Isolate the staging server from the network' is incorrect because isolating the server is a disruptive containment measure that should only be executed after an incident is confirmed, not during initial triaging of potentially authorized activity.\n\n'Begin full forensic imaging of the database server' is incorrect because full forensic imaging is resource-intensive and premature before confirming that an actual security incident has occurred.",
        "The correct answer is 'Revoke the compromised service account credentials' because it stops the ongoing unauthorized access directly at the source while minimizing disruption to other database users and services.\n\n'Notify law enforcement of the data breach' is incorrect because while law enforcement notification may be legally required later, it is a reporting action, not an immediate technical containment step to stop the breach.\n\n'Wipe the staging server to prevent exfiltration' is incorrect because wiping the server destroys vital forensic evidence needed for investigation and does not stop the attacker from exploiting the compromised credentials elsewhere.\n\n'Shut down the entire database cluster' is incorrect because shutting down the entire database cluster violates the principle of minimizing business impact during containment, as it stops all legitimate operations.",
        "The correct answer is 'Implement behavioral analytics on service account activity' because it establishes baselines for machine-to-machine interactions and can automatically detect and alert on anomalous queries that deviate from normal patterns.\n\n'Add network segmentation between all servers' is incorrect because broad network segmentation is highly disruptive and may not stop a service account that legitimately requires access to multiple servers to function.\n\n'Increase password complexity requirements' is incorrect because password complexity does not stop an attacker who has already compromised the existing credentials and is actively using them.\n\n'Require MFA for all service accounts' is incorrect because service accounts are typically used for automated, non-interactive processes where manual MFA implementation is technically infeasible."
    ],
    258: [
        "The correct answer is 'The volume and type of personal data affected' because understanding what specific personal data and how much of it is affected directly determines the organization's exposure to GDPR compliance risks and the necessary scope of remediation.\n\n'The startup's employee retention rates' is incorrect because while employee retention is a business risk in acquisitions, it is not a critical security or compliance risk that demands immediate assessment compared to legal liability from data exposure.\n\n'Whether the startup's code is well-documented' is incorrect because poor code documentation is a technical debt issue but does not carry the immediate, severe regulatory penalties associated with GDPR violations.\n\n'Network bandwidth between the two organizations' is incorrect because network bandwidth is an operational IT concern for post-acquisition integration, not a critical legal or security risk that must be assessed first.",
        "The correct answer is 'Standard Contractual Clauses for international transfers' because SCCs are a legally binding, GDPR-approved mechanism for ensuring that personal data transferred to a jurisdiction without adequate data protection laws remains properly safeguarded.\n\n'An agreement to delete all data post-acquisition' is incorrect because deleting all data destroys the value of the acquired company and is a destructive business decision rather than a compliance mechanism.\n\n'A verbal commitment from startup leadership' is incorrect because verbal commitments are not legally enforceable and completely fail to meet GDPR requirements for international data transfers.\n\n'A mutual NDA between both companies' is incorrect because a Non-Disclosure Agreement protects intellectual property and trade secrets between the companies; it does not satisfy regulatory requirements for protecting consumer personal data.",
        "The correct answer is 'Migrate personal data to a GDPR-compliant jurisdiction' because data residency is the primary compliance gap under GDPR. Migrating the data to a compliant jurisdiction immediately reduces legal exposure and fulfills regulatory requirements.\n\n'Upgrade the startup's hardware infrastructure' is incorrect because upgrading hardware is an operational improvement that does nothing to resolve the severe legal and regulatory risks of improper data residency.\n\n'Rebrand the startup's customer portal' is incorrect because rebranding is a cosmetic marketing activity and takes lower priority than resolving a critical regulatory compliance violation.\n\n'Integrate the startup's codebase into yours' is incorrect because integrating the codebase before resolving data residency could spread the compliance risk to the parent organization's existing systems."
    ],
    259: [
        "The correct answer is 'Implement tiered encryption based on data sensitivity' because tiered encryption applies the strongest cryptographic protection only to sensitive data, maintaining high performance and reducing latency for non-sensitive operations.\n\n'Skip encryption since performance matters more' is incorrect because skipping encryption entirely prioritizes performance at the expense of security, leaving sensitive transaction data vulnerable to interception.\n\n'Accept the latency increase without modification' is incorrect because accepting a 40% latency increase without exploring alternatives fails to balance security with the business requirement of processing 10,000 transactions per minute.\n\n'Encrypt only data at rest and skip in-transit encryption' is incorrect because skipping in-transit encryption leaves transaction data vulnerable to man-in-the-middle attacks over the network, failing to meet the security team's requirement.",
        "The correct answer is 'Implement hardware security modules for crypto offload' because HSMs or hardware acceleration offload cryptographic processing from the application servers' CPUs, significantly reducing the latency impact of encryption.\n\n'Reduce the number of daily transactions allowed' is incorrect because reducing daily transactions artificially limits business revenue and growth, making it an unacceptable solution to a technical performance issue.\n\n'Use weaker encryption algorithms for speed' is incorrect because using weaker, deprecated encryption algorithms compromises the security integrity of the platform and may violate compliance standards like PCI DSS.\n\n'Disable encryption during peak business hours' is incorrect because disabling encryption during peak hours leaves the platform most vulnerable precisely when the most transactions and sensitive data are flowing.",
        "The correct answer is 'Revenue impact of latency vs. cost of a breach' because quantifying the potential revenue lost due to latency against the potential financial impact of a data breach provides a clear, risk-based financial tradeoff for management.\n\n'Total number of employees in the company' is incorrect because the number of employees is irrelevant to the technical and financial risks of database encryption latency versus transaction security.\n\n'Competitor pricing comparison data' is incorrect because while competitive analysis is useful for business strategy, it does not justify an internal risk decision regarding encryption performance tradeoffs.\n\n'The age of the current server hardware' is incorrect because server age is an IT lifecycle metric and does not directly justify the financial risk tradeoff between data security and application latency."
    ],
    260: [
        "The correct answer is 'Traffic routing through unencrypted paths' because having dual active paths creates a risk that sensitive traffic might be misrouted over the unencrypted MPLS path or an improperly configured SD-WAN path if policies are not consistently enforced.\n\n'Incompatible monitor resolutions at branches' is incorrect because monitor resolution is a local hardware issue entirely unrelated to network routing and communication security.\n\n'Slower internet browsing speeds for users' is incorrect because slower browsing speeds are a performance or quality-of-service issue, not a primary security vulnerability.\n\n'Increased electricity costs at branch offices' is incorrect because electricity costs are an operational facility expense and have no bearing on network attack surfaces or data confidentiality.",
        "The correct answer is 'Mandatory encryption for all inter-site traffic' because enforcing mandatory encryption (like IPsec) on the SD-WAN overlay ensures that data remains confidential regardless of which physical underlay path the traffic takes.\n\n'Quality of service for video calls' is incorrect because Quality of Service (QoS) ensures performance for specific applications like video calls, but provides no security or confidentiality benefits.\n\n'Custom DNS for internal hostname resolution' is incorrect because custom DNS resolves internal hostnames but does not protect the data payload of the traffic traversing the new network architecture.\n\n'Bandwidth throttling for social media sites' is incorrect because bandwidth throttling manages network capacity by limiting certain traffic types, but it is an operational control, not a security control.",
        "The correct answer is 'Apply identical policies to both MPLS and SD-WAN paths' because applying identical, consistent security policies across both the MPLS and SD-WAN paths ensures there are no security gaps or bypasses while both connections are active.\n\n'Allow all traffic to prevent connectivity issues' is incorrect because allowing all traffic explicitly disables the firewall's security function, leaving the branch office completely vulnerable to attacks.\n\n'Remove all existing rules and start fresh' is incorrect because removing existing rules without a transition plan breaks connectivity and removes established security boundaries prematurely.\n\n'Disable them until migration completes' is incorrect because disabling firewalls entirely removes network perimeter defenses, vastly increasing the attack surface during a vulnerable transition period."
    ],
    261: [
        "The correct answer is 'Static RBAC struggles with users needing multiple roles' because traditional, static Single-Role RBAC models lack the flexibility to assign multiple concurrent roles, failing to accommodate users like the doctor who legitimately perform distinct job functions.\n\n'RBAC cannot handle any healthcare use cases' is incorrect because RBAC is widely and successfully used in healthcare; the issue is specifically with overly rigid, single-role implementations, not the RBAC concept itself.\n\n'The EHR system has too many features' is incorrect because the number of features in the system is irrelevant; the problem lies in how access to those features is authorized and managed.\n\n'Role-based access is inherently insecure' is incorrect because RBAC is a highly secure and standard access control model; it is not inherently insecure, just potentially inflexible if poorly designed.",
        "The correct answer is 'Implement composite roles or attribute-based policies' because Attribute-Based Access Control (ABAC) or composite roles provide the flexibility to grant access dynamically based on a user's multiple duties while maintaining the principle of least privilege.\n\n'Create a separate account for each role' is incorrect because creating multiple accounts for one user violates identity management best practices, complicates auditing, and increases the risk of credential compromise.\n\n'Remove RBAC and use discretionary access' is incorrect because Discretionary Access Control (DAC) relies on data owners to manage permissions, which is unscalable and insecure for a highly regulated EHR system.\n\n'Give the doctor full administrator access' is incorrect because granting full administrator access grossly violates the principle of least privilege and introduces massive risk to patient data integrity and confidentiality.",
        "The correct answer is 'Privilege accumulation violating separation of duties' because assigning multiple roles increases the risk of privilege creep, where accumulated permissions may conflict and violate Separation of Duties (SoD), requiring strict auditing.\n\n'Network latency between hospital floors' is incorrect because network latency is a physical infrastructure performance issue and is entirely unrelated to logical access control models.\n\n'The system might run out of storage space' is incorrect because logical role assignments consume negligible storage space; storage capacity is an irrelevant operational concern here.\n\n'The doctor might forget their password' is incorrect because while password resets are a common helpdesk issue, they are not a critical security risk introduced by multi-role access compared to privilege accumulation."
    ],
    262: [
        "The correct answer is 'Document the finding and stop testing that vector' because the tester must strictly adhere to the rules of engagement (RoE). Since exploiting patient data is explicitly prohibited, they must document the vulnerability and stop testing that specific vector.\n\n'Ignore it since it's out of scope entirely' is incorrect because the vulnerability is highly critical and within the application's scope; it must be documented and reported, not ignored.\n\n'Exploit it to prove the severity conclusively' is incorrect because exploiting the vulnerability directly violates the agreed-upon rules of engagement and could result in legal liability for the tester.\n\n'Notify the media about the vulnerability' is incorrect because notifying the media is highly unethical, breaches confidentiality agreements, and causes severe reputational damage.",
        "The correct answer is 'Immediately notify the designated point of contact' because a critical vulnerability that exposes millions of patient records poses an imminent threat to the organization and warrants immediate out-of-band notification to the designated contact.\n\n'Send it to a bug bounty platform instead' is incorrect because the engagement is an authorized pentest under a contract, not a public bug bounty program; sharing findings externally violates confidentiality.\n\n'Wait until the final report in two weeks' is incorrect because waiting two weeks leaves a highly critical, mass-exposure vulnerability unpatched in a production environment, representing unacceptable risk.\n\n'Post it on social media as a warning' is incorrect because posting findings publicly is a severe breach of professional ethics, non-disclosure agreements, and puts the client at immediate risk of real-world exploitation.",
        "The correct answer is 'Deploy a WAF rule to block the attack pattern' because deploying a Web Application Firewall (WAF) rule provides a fast, immediate compensating control to block exploitation attempts while developers work on a permanent code-level fix.\n\n'Ignore it until the pentest is fully complete' is incorrect because ignoring a critical production vulnerability while waiting for a formal report leaves 2 million patient records completely exposed to attackers.\n\n'Shut down the entire patient portal permanently' is incorrect because shutting down the entire portal causes severe disruption to patient care and operations; a WAF rule is a much less disruptive containment strategy.\n\n'Fire the developer who wrote the code' is incorrect because firing the developer is a punitive HR action, not a technical containment or mitigation step, and it does not fix the active vulnerability."
    ],
    263: [
        "The correct answer is 'The XSS manifests only through runtime DOM interaction' because stored XSS often involves complex data flows where malicious input is saved in a database and later rendered in a browser DOM. SAST analyzes static code and often struggles to accurately model these runtime, multi-tier interactions.\n\n'DAST always finds more vulnerabilities than SAST' is incorrect because DAST and SAST find different classes of vulnerabilities; neither inherently finds 'more' than the other. SAST is better at finding hardcoded secrets, while DAST excels at runtime flaws.\n\n'The SAST tool was not running during the scan' is incorrect because the scenario explicitly states that the code passed the SAST scans, meaning the tool was running but failed to detect the flaw.\n\n'SAST tools are completely unreliable' is incorrect because SAST tools are highly reliable for certain vulnerability classes (like syntax errors or basic injection flaws); they simply have limitations regarding runtime context.",
        "The correct answer is 'Delay release until the vulnerability is remediated' because stored XSS is a high-severity vulnerability that allows attackers to execute malicious scripts in users' browsers. Releasing known high-severity vulnerabilities into production is unacceptable risk management.\n\n'Remove the feature and release without it' is incorrect because while removing the feature mitigates the risk, delaying the release to properly fix the vulnerability is a more balanced approach that still delivers business value.\n\n'Release on schedule since it passed SAST' is incorrect because releasing solely because it passed SAST ignores the valid, critical finding from DAST, exposing production users to immediate risk.\n\n'Release and fix it in a future sprint' is incorrect because releasing a known, easily exploitable stored XSS vulnerability with a promise to fix it later recklessly endangers users and the organization's reputation.",
        "The correct answer is 'Run DAST earlier in the pipeline on feature branches' because shifting DAST testing 'left' to run earlier in the CI/CD pipeline (e.g., on feature branches or local staging) ensures runtime vulnerabilities are caught before the stressful final release phase.\n\n'Only perform manual code reviews' is incorrect because manual code reviews are slow, prone to human error, and do not scale; they should complement, not replace, automated testing.\n\n'Reduce the frequency of releases to quarterly' is incorrect because reducing release frequency slows down business agility and delays the deployment of potential security patches.\n\n'Remove SAST since DAST is sufficient alone' is incorrect because SAST and DAST are complementary. Removing SAST eliminates early detection of code-level flaws, weakening the overall security posture."
    ],
    264: [
        "The correct answer is 'Data is interwoven across multiple systems and stores' because CCPA requires complete data deletion, which is technically complex when customer data is deeply embedded and distributed across shared database indexes, immutable backup tapes, and aggregated analytics pipelines.\n\n'Multi-tenant databases cannot hold customer data' is incorrect because multi-tenant databases can hold and delete customer data, provided the architecture supports proper data segregation and tenant identification.\n\n'The engineering team lacks sufficient skills' is incorrect because the difficulty stems from architectural complexity, not necessarily the skill level of the engineering team.\n\n'The customer is too demanding' is incorrect because the customer is exercising a legal right granted by CCPA; compliance is mandatory, regardless of how demanding it seems.",
        "The correct answer is 'Document retention schedules and delete upon expiration' because it is generally technically infeasible to delete specific data from immutable offline backups. The standard approach is to document retention schedules, ensure the data is not restored, and let the data naturally age out and be destroyed.\n\n'Ignore backups since they don't count under CCPA' is incorrect because backups are definitely subject to CCPA regulations; ignoring them is a compliance violation.\n\n'Delete all backup tapes for all customers' is incorrect because deleting all backups for all customers destroys the company's disaster recovery capabilities and violates data availability requirements.\n\n'Create new backups excluding only this customer' is incorrect because creating entirely new backups from scratch and destroying old ones is extremely resource-intensive and operationally impractical for every single deletion request.",
        "The correct answer is 'Implement per-tenant encryption with unique keys' because using unique encryption keys for each tenant enables 'crypto-shredding.' When a customer requests deletion, destroying their unique key instantly renders all their data across all systems mathematically unrecoverable.\n\n'Store all data in a single unpartitioned table' is incorrect because storing data in a single unpartitioned table exacerbates the problem by making it harder to identify and isolate specific tenant data for deletion.\n\n'Stop accepting customers entirely' is incorrect because stopping business operations entirely is a commercial failure, not a viable architectural or technical strategy.\n\n'Move to a single-tenant database for every customer' is incorrect because moving to single-tenant databases for every customer dramatically increases infrastructure costs and operational overhead, destroying the economic model of SaaS."
    ],
    265: [
        "The correct answer is 'Backups were stored on the same network domain' because if the backup infrastructure relies on the same Active Directory domain for authentication, an attacker with Domain Admin credentials can seamlessly authenticate to and encrypt the backup servers as well.\n\n'The backup software had a user interface bug' is incorrect because the scenario specifies the root cause was the attacker gaining domain admin access, not a bug in the backup software itself.\n\n'The attacker was lucky with timing' is incorrect because successful ransomware deployment across primary and backup systems is the result of architectural design flaws and privileged access, not mere luck.\n\n'Backup tapes were physically too close to servers' is incorrect because physical proximity does not enable logical network encryption by ransomware; logical network access and shared authentication domains do.",
        "The correct answer is 'Check for offline or immutable backup copies' because offline, air-gapped, or immutable (WORM - Write Once Read Many) backups cannot be modified or encrypted over the network, making them the only reliable recovery source when the primary domain is compromised.\n\n'Rebuild all systems from scratch without data' is incorrect because rebuilding systems without restoring the data results in catastrophic data loss and does not meet the business's recovery objectives.\n\n'Wait for law enforcement to recover the keys' is incorrect because law enforcement rarely recovers decryption keys quickly enough to meet a 4-hour Recovery Time Objective (RTO).\n\n'Pay the ransom immediately' is incorrect because paying the ransom is strongly discouraged as it does not guarantee data recovery, funds criminal enterprises, and does not fix the underlying vulnerability.",
        "The correct answer is 'Implement immutable backups isolated from the domain' because storing immutable backups on an infrastructure that is logically isolated and not joined to the primary Active Directory domain ensures that compromised domain credentials cannot be used to destroy the backups.\n\n'Store backups on the same server for faster access' is incorrect because storing backups on the same server guarantees they will be encrypted simultaneously with the primary data, defeating the purpose of a backup.\n\n'Use stronger passwords for domain admins' is incorrect because while good practice, strong passwords do not prevent attackers from stealing hashes, using pass-the-hash techniques, or exploiting other vulnerabilities to gain domain admin.\n\n'Increase backup frequency to every hour' is incorrect because taking backups more frequently does not protect them; the attacker will simply encrypt the more frequent backups if they are on the same compromised domain."
    ],
    266: [
        "The correct answer is 'Use Monte Carlo simulation with industry benchmarks' because Monte Carlo simulations are ideal for scenarios with sparse historical data because they use probability distributions and industry benchmark ranges to run thousands of scenarios, outputting a statistically sound range of potential outcomes.\n\n'Calculate simple ALE from only internal incidents' is incorrect because calculating Annualized Loss Expectancy (ALE) based on only three internal incidents over five years yields a statistically insignificant and highly inaccurate point estimate.\n\n'State that risk cannot be quantified at all' is incorrect because while difficult, risk can and must be quantified to support business decision-making; completely refusing to try is a failure of security leadership.\n\n'Report zero risk since incidents are rare' is incorrect because the absence of frequent past incidents does not equal the absence of future risk; reporting zero risk is dangerously misleading to the board.",
        "The correct answer is 'Provide ranges with explicit confidence intervals' because presenting risk as a range (e.g., '$5M - $15M') with a stated confidence interval (e.g., '90% confidence') honestly communicates the inherent uncertainty of the model to the board.\n\n'Present numbers as exact and certain' is incorrect because presenting point estimates as exact facts creates false precision and sets the CISO up for failure if an incident exceeds that specific number.\n\n'Only share results if they show low risk' is incorrect because withholding risk information because it shows high risk is a severe breach of transparency and fiduciary duty to the board.\n\n'Avoid presenting any numbers to the board' is incorrect because the board specifically requested financial quantification; ignoring the request fails to support executive oversight.",
        "The correct answer is 'Explain why a range is more accurate than a point estimate' because the CISO must educate the board that cybersecurity risk deals with complex variables and uncertainties. Providing a single point estimate is mathematically flawed and misleading, whereas a range reflects reality.\n\n'Delegate the presentation to an external consultant' is incorrect because the CISO is responsible for communicating security risk to the board; delegating it evades core leadership responsibilities.\n\n'Refuse to present any quantitative information' is incorrect because refusing to present data is uncooperative and fails to fulfill the board's legitimate request for risk visibility.\n\n'Provide whatever number the board wants to hear' is incorrect because providing an arbitrary number just to appease the board is unethical and leads to poorly informed business decisions."
    ],
    267: [
        "The correct answer is 'Traffic flows were not fully mapped before enforcement' because microsegmentation strictly enforces 'default deny' policies. If legitimate application traffic flows were not exhaustively mapped and explicitly permitted before enforcement, the firewall will block them, breaking services.\n\n'The network hardware is incompatible' is incorrect because the scenario describes a configuration and policy issue (blocking legitimate traffic), not a hardware compatibility failure.\n\n'Developers intentionally broke their own services' is incorrect because blaming developers is unprofessional and highly unlikely; the issue clearly stems from the newly implemented security controls blocking traffic.\n\n'Microsegmentation cannot work in data centers' is incorrect because microsegmentation is highly effective in data centers; the failure here was in the execution and implementation process, not the technology itself.",
        "The correct answer is 'Switch blocked segments to monitor-only mode' because reverting the specific blocking segments to 'monitor-only' or 'alert-only' mode immediately restores business services while allowing the security team to log and analyze the legitimate flows that were missed.\n\n'Allow all traffic until developers stop complaining' is incorrect because allowing all traffic globally defeats the entire purpose of the microsegmentation project and removes all security boundaries.\n\n'Remove microsegmentation entirely and permanently' is incorrect because tearing out the entire solution is a massive overreaction to a fixable policy tuning issue.\n\n'Disable all network security controls' is incorrect because disabling all network security controls is a reckless action that leaves the entire data center vulnerable to attack.",
        "The correct answer is 'Extended observation period to baseline all traffic flows' because best practice for microsegmentation requires deploying policies in a 'monitor-only' mode for an extended baseline period to discover and map all legitimate application flows before switching to 'enforcement' mode.\n\n'Skip testing and enforce immediately' is incorrect because enforcing without testing directly caused the current outage; repeating this process guarantees future failures.\n\n'Only deploy during holiday periods' is incorrect because while deploying during low-traffic periods reduces immediate impact, it does not solve the root cause of incomplete policy mapping and will just break services when normal traffic resumes.\n\n'Require developers to memorize all port numbers' is incorrect because relying on human memory for complex network flows is prone to error; automated discovery and baselining are required."
    ],
    268: [
        "The correct answer is 'HR-to-IT offboarding workflow was not timely' because the root cause is a breakdown in the offboarding process. IT was not notified, or did not act quickly enough, to disable access upon termination, leaving the credentials active and vulnerable.\n\n'The VPN software has a critical bug' is incorrect because the VPN software functioned exactly as designed by authenticating a valid, active set of credentials; the issue is that the credentials should have been disabled.\n\n'Foreign IP addresses should never connect to VPN' is incorrect because while geoblocking is a valid control, the primary failure here is that a terminated employee's account was still active, regardless of where the connection originated.\n\n'The employee had too many vacation days' is incorrect because an employee's vacation balance has no technical or procedural relevance to timely access revocation upon termination.",
        "The correct answer is 'Disable the account and terminate active sessions' because the immediate priority during an active unauthorized access event is to cut off the attacker by disabling the compromised account and forcibly killing all active VPN sessions associated with it.\n\n'Block the foreign country at the firewall' is incorrect because blocking the country is too slow, easily bypassed by the attacker using a different proxy, and may inadvertently block legitimate global business traffic.\n\n'Wait to see what the attacker does next' is incorrect because passively watching an attacker who is actively authenticated to the internal network allows them time to move laterally and exfiltrate data.\n\n'Send a warning email to the former employee' is incorrect because sending an email to an attacker is ineffective and tips them off that they have been detected, causing them to accelerate their attack or hide their tracks.",
        "The correct answer is 'Automated deprovisioning triggered by HR termination' because automating the workflow so that an HR termination status directly triggers immediate access revocation in Identity and Access Management (IAM) systems eliminates human delays and errors.\n\n'Require employees to return badges faster' is incorrect because returning a physical badge does not revoke logical network access, leaving VPN and cloud accounts vulnerable.\n\n'Manual weekly reviews of all user accounts' is incorrect because weekly reviews are far too slow; an attacker or malicious insider can cause catastrophic damage in the days before a weekly review catches the active account.\n\n'Longer notice periods for departing employees' is incorrect because longer notice periods do not fix the technical disconnect between HR systems and IT access control systems upon the actual date of departure."
    ],
    269: [
        "The correct answer is 'Implement Transparent Data Encryption (TDE)' because TDE encrypts data at the file/storage level seamlessly. The database engine handles encryption/decryption in real-time as data is read/written, requiring no application changes and minimal, if any, downtime to implement on existing systems.\n\n'Skip encryption entirely due to the constraint' is incorrect because skipping encryption violates HIPAA compliance requirements and leaves massive amounts of sensitive patient data exposed.\n\n'Delete old records to reduce encryption time' is incorrect because deleting medical records to save time violates data retention laws and destroys critical patient health history.\n\n'Encrypt only new records going forward' is incorrect because encrypting only new records leaves the massive legacy database of 50TB of patient records completely vulnerable and non-compliant.",
        "The correct answer is 'Separate key management from database administrators' because the principle of Separation of Duties dictates that Database Administrators (who control the data) should not also have access to the cryptographic keys. If a DBA's account is compromised, the attacker cannot steal both the encrypted data and the key to decrypt it.\n\n'Store keys in the same database as the data' is incorrect because storing the key alongside the data it protects defeats the purpose of encryption, as an attacker stealing the database file gets the key too.\n\n'Use the same key for all databases' is incorrect because using a single master key for all databases creates a massive single point of failure; if compromised, all systems are exposed.\n\n'Use short keys to improve query performance' is incorrect because using short keys drastically weakens cryptographic strength, making the data vulnerable to brute-force attacks and violating modern security standards.",
        "The correct answer is 'HIPAA technical safeguard for data at rest protection' because the Health Insurance Portability and Accountability Act (HIPAA) Security Rule explicitly requires covered entities to implement technical safeguards, such as encryption, to protect electronic Protected Health Information (ePHI) at rest.\n\n'PCI DSS network segmentation rules' is incorrect because the scenario discusses database encryption (data at rest), not network segmentation rules for payment card data.\n\n'FERPA student record access controls' is incorrect because FERPA applies to educational records, not the patient health records managed by a healthcare organization.\n\n'SOX financial reporting accuracy requirements' is incorrect because SOX applies to the accuracy and integrity of corporate financial reporting, not the confidentiality of patient medical data."
    ],
    270: [
        "The correct answer is 'Exploitability combined with business impact of affected assets' because risk is a function of likelihood (how easily the vulnerability can be exploited) and impact (the value and criticality of the compromised asset). Prioritizing based on this intersection ensures the most dangerous threats to the business are mitigated first.\n\n'The seniority of the system owners involved' is incorrect because security prioritization should be based on objective risk to the organization, not internal politics or the rank of the asset owner.\n\n'Which fixes are cheapest to implement' is incorrect because fixing cheap, low-risk issues while ignoring difficult, high-risk vulnerabilities provides a false sense of security and leaves the organization exposed.\n\n'Which vulnerabilities were found first chronologically' is incorrect because chronological discovery order has no correlation with the severity of the vulnerability or the risk to the business.",
        "The correct answer is 'Document them in the risk register with formal acceptance' because vulnerabilities that cannot be fixed due to resource constraints must be formally documented in the risk register, assessed for impact, and officially accepted by business leadership to ensure accountability.\n\n'Delete them from the report entirely' is incorrect because deleting findings falsifies the security assessment, hides risk from leadership, and violates professional ethics.\n\n'Ignore them until next year's pentest' is incorrect because ignoring known vulnerabilities without formal risk acceptance represents negligent security management and leaves the organization unknowingly exposed.\n\n'Mark them as resolved without fixing them' is incorrect because marking unfixed issues as resolved is actively deceptive and destroys the integrity of the organization's vulnerability management program.",
        "The correct answer is 'Retest of accepted risks plus new scope areas' because a retest validates that the 20 fixes were actually effective, re-evaluates the 27 accepted risks to ensure their threat level hasn't increased, and covers new application changes made over the year.\n\n'No pentest since findings aren't being fixed anyway' is incorrect because canceling testing because previous issues remain unfixed ensures that new, potentially more critical vulnerabilities will go entirely undetected.\n\n'The exact same test repeated identically' is incorrect because repeating the exact same test ignores environmental changes, new threat vectors, and newly deployed code, rendering the assessment outdated and incomplete.\n\n'A less thorough test to find fewer issues' is incorrect because mandating a less thorough test simply to generate a cleaner report is a severe security failure that intentionally blinds the organization to actual risk."
    ],
    271: [
        "The correct answer is 'Implement compensating controls around the vulnerability' because since a patch is unavailable, implementing compensating controls (like strict input validation, Web Application Firewall rules to block exploit patterns, or enhanced monitoring) immediately reduces the risk of exploitation while a permanent solution is developed.\n\n'Switch to an unvetted library found on GitHub' is incorrect because introducing unvetted, potentially malicious code from a random GitHub repository introduces extreme, unknown risks that are likely worse than the known vulnerability.\n\n'Remove the payment feature from the application' is incorrect because removing core business functionality like payments is a catastrophic disruption to the business and should only be a last resort.\n\n'Continue using the library and hope for the best' is incorrect because continuing to use a library with a known authentication bypass vulnerability without applying compensating controls is negligent and guarantees eventual exploitation.",
        "The correct answer is 'Fork the library and apply the fix internally' because forking the open-source library allows the internal development team to apply a targeted patch for the specific CVE, maintaining the required payment functionality while securing the application.\n\n'Wait indefinitely for the maintainer to respond' is incorrect because waiting indefinitely leaves the application permanently vulnerable; organizations must take ownership of the security of their dependencies.\n\n'Rewrite the entire application from scratch' is incorrect because rewriting the entire application is an massive overreaction to a single vulnerable third-party library and wastes tremendous engineering resources.\n\n'Ignore the CVE since no exploit exists publicly' is incorrect because the absence of a public exploit does not mean the vulnerability cannot be exploited; attackers frequently reverse-engineer CVEs to create private exploits.",
        "The correct answer is 'Implement automated dependency scanning in CI/CD' because integrating Software Composition Analysis (SCA) into the CI/CD pipeline automatically scans all third-party libraries for known CVEs, preventing vulnerable dependencies from being deployed to production in the future.\n\n'Disable all automated security tooling' is incorrect because disabling security tooling guarantees that future vulnerabilities will be deployed blindly into production.\n\n'Only use libraries written in-house' is incorrect because banning all third-party libraries is technically and economically unfeasible; it would drastically slow development speed and increase costs.\n\n'Never use third-party libraries again' is incorrect because modern software development relies heavily on open-source ecosystems for efficiency."
    ]
}

for item in data:
    if item['type'] == 'scenario':
        s_id = item['id']
        if s_id in replacements:
            for q_idx, q in enumerate(item['questions']):
                q['exp'] = replacements[s_id][q_idx]

with open('c:\\projects\\cissp\\scenarios_fixed_1.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2)

print("Done")
