import json

questions = []
id_counter = 11381

def q_ms(domain, text, options, answers, explanation):
    global id_counter
    questions.append({"id": id_counter, "domain": str(domain), "format": "ms", "text": text, "options": options, "answers": answers, "explanation": explanation})
    id_counter += 1

def q_order(domain, text, options, answers, explanation):
    global id_counter
    questions.append({"id": id_counter, "domain": str(domain), "format": "order", "text": text, "options": options, "answers": answers, "explanation": explanation})
    id_counter += 1

# Domain 1 (6 ms, 4 order)
q_ms(1, "Which of the following are components of the CIA triad? (Select THREE)", ["Confidentiality", "Integrity", "Accountability", "Availability", "Authentication"], ["Confidentiality", "Integrity", "Availability"], "The CIA triad consists of Confidentiality, Integrity, and Availability.")
q_ms(1, "Which of the following are elements of the STRIDE threat model? (Select TWO)", ["Spoofing", "Tampering", "Ransomware", "Eavesdropping", "Phishing"], ["Spoofing", "Tampering"], "STRIDE stands for Spoofing, Tampering, Repudiation, Information Disclosure, Denial of Service, and Elevation of Privilege.")
q_ms(1, "Which of the following frameworks are primarily focused on risk management? (Select TWO)", ["NIST SP 800-37", "ISO 31000", "OSI Model", "TCP/IP", "IEEE 802.11"], ["NIST SP 800-37", "ISO 31000"], "NIST SP 800-37 and ISO 31000 are well-known risk management frameworks.")
q_ms(1, "Which of the following are quantitative risk analysis metrics? (Select TWO)", ["SLE", "ALE", "High/Medium/Low", "Delphi method", "Red/Yellow/Green"], ["SLE", "ALE"], "Single Loss Expectancy (SLE) and Annualized Loss Expectancy (ALE) are quantitative metrics.")
q_ms(1, "Which of the following legal systems are based on rules created by legislative bodies rather than precedent? (Select TWO)", ["Civil Law", "Common Law", "Customary Law", "Code Law", "Religious Law"], ["Civil Law", "Code Law"], "Civil Law (or Code Law) is rule-based, whereas Common Law relies on precedent.")
q_ms(1, "Which of the following are valid types of access control categories? (Select THREE)", ["Administrative", "Technical", "Physical", "Mandatory", "Discretionary"], ["Administrative", "Technical", "Physical"], "Administrative, Technical (Logical), and Physical are categories of access controls (Directive, Deterrent, etc., are types).")

q_order(1, "Order the steps of the Business Continuity Planning (BCP) process.", ["Project Initiation", "Business Impact Analysis (BIA)", "Recovery Strategy Development", "Plan Design and Development", "Testing, Maintenance, and Updating"], ["Project Initiation", "Business Impact Analysis (BIA)", "Recovery Strategy Development", "Plan Design and Development", "Testing, Maintenance, and Updating"], "The BCP process starts with initiation, follows with BIA, strategy development, plan design, and ends with testing/maintenance.")
q_order(1, "Order the steps of the Risk Management Framework (RMF).", ["Categorize", "Select", "Implement", "Assess", "Authorize", "Monitor"], ["Categorize", "Select", "Implement", "Assess", "Authorize", "Monitor"], "The RMF steps are Categorize, Select, Implement, Assess, Authorize, and Monitor.")
q_order(1, "Order the standard stages of the incident classification process.", ["Detection", "Triage", "Analysis", "Classification", "Prioritization"], ["Detection", "Triage", "Analysis", "Classification", "Prioritization"], "Events must be detected, triaged, analyzed, then classified and prioritized.")
q_order(1, "Order the steps of a typical Information Security Strategy planning process.", ["Assess Current State", "Define Future State", "Identify Gaps", "Develop Action Plan", "Execute and Monitor"], ["Assess Current State", "Define Future State", "Identify Gaps", "Develop Action Plan", "Execute and Monitor"], "Strategy planning involves understanding the present, defining the future, finding gaps, planning actions, and executing.")

# Domain 2 (6 ms, 4 order)
q_ms(2, "Which of the following are responsibilities of a Data Owner? (Select TWO)", ["Classifying data", "Performing backups", "Determining access rights", "Configuring firewalls", "Patching servers"], ["Classifying data", "Determining access rights"], "Data Owners classify data and determine who has access; Custodians perform technical implementation.")
q_ms(2, "Which of the following are valid data destruction methods for magnetic media? (Select THREE)", ["Degaussing", "Incineration", "Formatting", "Shredding", "Deleting"], ["Degaussing", "Incineration", "Shredding"], "Formatting and deleting do not securely destroy data on magnetic media.")
q_ms(2, "Which of the following are core components of privacy regulations like GDPR? (Select TWO)", ["Right to be forgotten", "Mandatory AES-256 encryption", "Data portability", "Use of biometric access", "Annual penetration testing"], ["Right to be forgotten", "Data portability"], "The Right to be forgotten and Data portability are key privacy rights under GDPR.")
q_ms(2, "Which of the following are characteristics of data remanence? (Select TWO)", ["It can lead to data leakage", "It occurs when data is not fully erased", "It is prevented by standard deletion", "It only applies to cloud storage", "It is desirable for data retention"], ["It can lead to data leakage", "It occurs when data is not fully erased"], "Data remanence is the residual representation of digital data that remains even after attempts have been made to remove or erase it.")
q_ms(2, "Which of the following are data states? (Select THREE)", ["Data at rest", "Data in transit", "Data in use", "Data in metadata", "Data in cache"], ["Data at rest", "Data in transit", "Data in use"], "The three primary states of data are at rest, in transit (motion), and in use.")
q_ms(2, "Which of the following terms refer to the anonymization of data? (Select TWO)", ["Masking", "Tokenization", "Encryption", "Hashing", "Obfuscation"], ["Masking", "Tokenization"], "Masking and tokenization are methods used to protect and anonymize data while retaining its format or utility.")

q_order(2, "Order the typical data lifecycle stages.", ["Create", "Store", "Use", "Share", "Archive", "Destroy"], ["Create", "Store", "Use", "Share", "Archive", "Destroy"], "The standard data lifecycle is Create, Store, Use, Share, Archive, and Destroy.")
q_order(2, "Order the steps of a typical data classification process.", ["Identify Data", "Determine Ownership", "Classify Data", "Apply Security Controls", "Review Classification"], ["Identify Data", "Determine Ownership", "Classify Data", "Apply Security Controls", "Review Classification"], "First data is identified, then an owner is determined, it is classified, controls are applied, and it is periodically reviewed.")
q_order(2, "Order the hierarchy of commercial data classification (from most to least sensitive).", ["Confidential", "Private", "Sensitive", "Public"], ["Confidential", "Private", "Sensitive", "Public"], "A common commercial classification hierarchy is Confidential, Private, Sensitive, Public.")
q_order(2, "Order the hierarchy of government/military data classification (from most to least sensitive).", ["Top Secret", "Secret", "Confidential", "Unclassified"], ["Top Secret", "Secret", "Confidential", "Unclassified"], "The government classification hierarchy is Top Secret, Secret, Confidential, Unclassified.")

# Domain 4 (6 ms, 4 order)
q_ms(4, "Which of the following protocols operate at the Transport Layer of the OSI model? (Select TWO)", ["TCP", "IP", "UDP", "HTTP", "ICMP"], ["TCP", "UDP"], "TCP and UDP operate at Layer 4 (Transport). IP and ICMP are Layer 3, HTTP is Layer 7.")
q_ms(4, "Which of the following are distance-vector routing protocols? (Select TWO)", ["RIP", "OSPF", "EIGRP", "BGP", "IS-IS"], ["RIP", "EIGRP"], "RIP and EIGRP are distance-vector protocols, while OSPF and IS-IS are link-state.")
q_ms(4, "Which of the following are types of firewalls? (Select THREE)", ["Packet filtering", "Stateful inspection", "Application layer proxy", "Distance-vector", "Link-state"], ["Packet filtering", "Stateful inspection", "Application layer proxy"], "Packet filtering, stateful inspection, and application layer proxy are common firewall types.")
q_ms(4, "Which of the following are valid IPsec sub-protocols? (Select TWO)", ["AH", "ESP", "SSL", "TLS", "IKE"], ["AH", "ESP"], "Authentication Header (AH) and Encapsulating Security Payload (ESP) are the core IPsec protocols. IKE is for key exchange.")
q_ms(4, "Which of the following attacks target the Network layer (Layer 3)? (Select TWO)", ["Ping of Death", "Smurf Attack", "SYN Flood", "SQL Injection", "Cross-Site Scripting"], ["Ping of Death", "Smurf Attack"], "Ping of Death and Smurf attacks use ICMP, which is at the Network layer. SYN Flood is Layer 4.")
q_ms(4, "Which of the following wireless encryption protocols are considered insecure and deprecated? (Select TWO)", ["WEP", "WPA", "WPA2", "WPA3", "802.1X"], ["WEP", "WPA"], "WEP and the original WPA (using TKIP) are deprecated and insecure.")

q_order(4, "Order the layers of the OSI model from Layer 1 to Layer 7.", ["Physical", "Data Link", "Network", "Transport", "Session", "Presentation", "Application"], ["Physical", "Data Link", "Network", "Transport", "Session", "Presentation", "Application"], "The OSI model layers are Physical, Data Link, Network, Transport, Session, Presentation, Application.")
q_order(4, "Order the steps of the TCP 3-way handshake.", ["SYN", "SYN-ACK", "ACK"], ["SYN", "SYN-ACK", "ACK"], "The TCP handshake consists of SYN, SYN-ACK, and ACK.")
q_order(4, "Order the layers of the TCP/IP model from lowest to highest.", ["Network Access", "Internet", "Transport", "Application"], ["Network Access", "Internet", "Transport", "Application"], "The TCP/IP model layers are Network Access (Link), Internet, Transport, and Application.")
q_order(4, "Order the data encapsulation units from OSI Layer 1 to Layer 4.", ["Bits", "Frames", "Packets", "Segments"], ["Bits", "Frames", "Packets", "Segments"], "Data is represented as Bits at L1, Frames at L2, Packets at L3, and Segments at L4.")

# Domain 7 (6 ms, 4 order)
q_ms(7, "Which of the following are phases of the Incident Response lifecycle? (Select THREE)", ["Preparation", "Detection and Analysis", "Containment, Eradication, and Recovery", "System Development", "Risk Assessment"], ["Preparation", "Detection and Analysis", "Containment, Eradication, and Recovery"], "The NIST IR lifecycle includes Preparation, Detection/Analysis, Containment/Eradication/Recovery, and Post-Incident Activity.")
q_ms(7, "Which of the following are types of Disaster Recovery sites? (Select THREE)", ["Hot site", "Warm site", "Cold site", "Cloud site", "Frozen site"], ["Hot site", "Warm site", "Cold site"], "Hot, warm, and cold sites are standard physical DR site designations.")
q_ms(7, "Which of the following are examples of detective controls? (Select TWO)", ["Intrusion Detection System (IDS)", "Log monitoring", "Firewall", "Security Guard", "Encryption"], ["Intrusion Detection System (IDS)", "Log monitoring"], "IDS and log monitoring detect events after or as they occur, whereas firewalls and encryption are preventive.")
q_ms(7, "Which of the following are valid evidence types in a forensic investigation? (Select THREE)", ["Direct evidence", "Circumstantial evidence", "Corroborative evidence", "Hearsay evidence", "Fabricated evidence"], ["Direct evidence", "Circumstantial evidence", "Corroborative evidence"], "Direct, circumstantial, and corroborative are recognized types of legal evidence.")
q_ms(7, "Which of the following backup types clear the archive bit? (Select TWO)", ["Full backup", "Incremental backup", "Differential backup", "Copy backup", "Daily backup"], ["Full backup", "Incremental backup"], "Full and incremental backups clear the archive bit. Differential backups do not.")
q_ms(7, "Which of the following are components of Identity and Access Management (IAM) provisioning? (Select TWO)", ["Account creation", "Privilege assignment", "Vulnerability scanning", "Penetration testing", "Incident containment"], ["Account creation", "Privilege assignment"], "Provisioning involves creating accounts and assigning appropriate privileges.")

q_order(7, "Order the steps of the standard digital forensics process.", ["Identification", "Collection", "Examination", "Analysis", "Reporting"], ["Identification", "Collection", "Examination", "Analysis", "Reporting"], "The forensic process is Identification, Collection, Examination, Analysis, and Reporting.")
q_order(7, "Order the steps of the Incident Response Process (NIST).", ["Preparation", "Detection & Analysis", "Containment", "Eradication", "Recovery", "Post-Incident Activity"], ["Preparation", "Detection & Analysis", "Containment", "Eradication", "Recovery", "Post-Incident Activity"], "The process is Preparation, Detection & Analysis, Containment, Eradication, Recovery, and Post-Incident Activity.")
q_order(7, "Order the volatility of digital evidence from most volatile to least volatile.", ["CPU Cache", "RAM", "Swap Space", "Hard Drive", "Archival Media"], ["CPU Cache", "RAM", "Swap Space", "Hard Drive", "Archival Media"], "Evidence should be collected based on the order of volatility, starting with the most volatile.")
q_order(7, "Order the steps involved in eDiscovery.", ["Identification", "Preservation", "Collection", "Processing", "Review", "Analysis", "Production"], ["Identification", "Preservation", "Collection", "Processing", "Review", "Analysis", "Production"], "The EDRM steps include Identification, Preservation, Collection, Processing, Review, Analysis, and Production.")

# Domain 8 (6 ms, 4 order)
q_ms(8, "Which of the following are phases in the standard Software Development Life Cycle (SDLC)? (Select THREE)", ["Requirements Analysis", "Design", "Testing", "Incident Response", "Forensics"], ["Requirements Analysis", "Design", "Testing"], "Requirements Analysis, Design, and Testing are standard SDLC phases.")
q_ms(8, "Which of the following are common types of Cross-Site Scripting (XSS)? (Select TWO)", ["Stored (Persistent)", "Reflected (Non-Persistent)", "SQL Injection", "Buffer Overflow", "Command Injection"], ["Stored (Persistent)", "Reflected (Non-Persistent)"], "Stored and Reflected are the two most common types of XSS (along with DOM-based).")
q_ms(8, "Which of the following vulnerabilities are mitigated by using parameterized queries? (Select TWO)", ["SQL Injection", "LDAP Injection", "Cross-Site Scripting", "Cross-Site Request Forgery", "Buffer Overflow"], ["SQL Injection", "LDAP Injection"], "Parameterized queries prevent injection attacks by separating code and data.")
q_ms(8, "Which of the following are Agile development methodologies? (Select TWO)", ["Scrum", "Extreme Programming (XP)", "Waterfall", "Spiral", "V-Model"], ["Scrum", "Extreme Programming (XP)"], "Scrum and XP are Agile methodologies. Waterfall, Spiral, and V-Model are not.")
q_ms(8, "Which of the following are valid forms of application testing? (Select THREE)", ["Static Application Security Testing (SAST)", "Dynamic Application Security Testing (DAST)", "Interactive Application Security Testing (IAST)", "Forensic Application Testing (FAST)", "Cryptographic Application Testing (CAST)"], ["Static Application Security Testing (SAST)", "Dynamic Application Security Testing (DAST)", "Interactive Application Security Testing (IAST)"], "SAST, DAST, and IAST are recognized forms of application security testing.")
q_ms(8, "Which of the following principles belong to the OWASP Top 10? (Select TWO)", ["Injection", "Broken Authentication", "Denial of Service", "Buffer Overflow", "Zero-day Exploits"], ["Injection", "Broken Authentication"], "Injection and Broken Authentication are consistently featured in the OWASP Top 10.")

q_order(8, "Order the phases of the Software Development Life Cycle (SDLC).", ["Requirements Gathering", "Design", "Development", "Testing", "Deployment", "Maintenance"], ["Requirements Gathering", "Design", "Development", "Testing", "Deployment", "Maintenance"], "A typical SDLC moves from Requirements to Design, Development, Testing, Deployment, and Maintenance.")
q_order(8, "Order the levels of the Capability Maturity Model Integration (CMMI).", ["Initial", "Managed", "Defined", "Quantitatively Managed", "Optimizing"], ["Initial", "Managed", "Defined", "Quantitatively Managed", "Optimizing"], "The CMMI levels are Initial (1), Managed (2), Defined (3), Quantitatively Managed (4), and Optimizing (5).")
q_order(8, "Order the steps for securely handling user passwords in an application.", ["Receive Password", "Generate Salt", "Hash Password with Salt", "Store Salt and Hash"], ["Receive Password", "Generate Salt", "Hash Password with Salt", "Store Salt and Hash"], "Passwords should be securely hashed and salted before storage.")
q_order(8, "Order the process of federated identity authentication (e.g., SAML).", ["User requests access to Service Provider", "Service Provider redirects to Identity Provider", "Identity Provider authenticates user", "Identity Provider sends token to Service Provider", "Service Provider grants access"], ["User requests access to Service Provider", "Service Provider redirects to Identity Provider", "Identity Provider authenticates user", "Identity Provider sends token to Service Provider", "Service Provider grants access"], "The SAML flow involves redirection to the IdP, authentication, token issuance, and subsequent access grant.")

# Write to file
with open(r'c:\projects\cissp\new_q_variety2.json', 'w') as f:
    json.dump(questions, f, indent=4)
